# Opus User C Module for MicroPython

# Define an INTERFACE library for this module
add_library(usermod_opus INTERFACE)

# Source files
# Opusmod main binding
set(OPUSMOD_BINDING_SOURCES
    ${CMAKE_CURRENT_LIST_DIR}/opusmod.c
)

# Opus library core sources (subset, fixed-point focus)
set(OPUS_CORE_SOURCES
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/opus.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/opus_decoder.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/opus_encoder.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/opus_multistream.c
    # ${CMAKE_CURRENT_LIST_DIR}/libopus/src/opus_multistream_decoder.c # Likely not needed
    # ${CMAKE_CURRENT_LIST_DIR}/libopus/src/opus_multistream_encoder.c # Likely not needed
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/repacketizer.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/analysis.c # Check if suitable for fixed point
    # MLP is part of the new Neural PLC, might be complex for MCU. Consider removing.
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/mlp.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/mlp_data.c
)

# CELT sources (user must place these files in libopus/src/celt/)
# User must ensure these are appropriate for fixed-point build.
# This list should ideally be generated by Opus's build system for a fixed-point config.
set(CELT_SOURCES
    # Example, actual files depend on Opus version and fixed-point configuration
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/celt/bands.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/celt/celt.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/celt/celt_decoder.c # Ensure this is the non-float version or fixed-point version
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/celt/celt_encoder.c # Ensure this is the non-float version or fixed-point version
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/celt/celt_lpc.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/celt/cwrs.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/celt/entcode.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/celt/entdec.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/celt/entenc.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/celt/kiss_fft.c # kiss_fft can be fixed or float, ensure fixed if used.
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/celt/laplace.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/celt/mathops.c # Should use fixed-point mathops
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/celt/mdct.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/celt/modes.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/celt/pitch.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/celt/quant_bands.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/celt/rate.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/celt/vq.c
)

# SILK sources (user must place these in libopus/src/silk/)
# Generic SILK sources
set(SILK_COMMON_SOURCES
    # Common SILK files from the original list, excluding float-specific ones
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/A2NLSF.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/CNG.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/LPC_analysis_filter.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/LPC_fit.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/LPC_inv_pred_gain.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/LP_variable_cutoff.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/NLSF2A.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/NLSF_VQ.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/NLSF_VQ_weights_laroia.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/NLSF_decode.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/NLSF_del_dec_quant.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/NLSF_encode.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/NLSF_stabilize.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/NLSF_unpack.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/NSQ.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/NSQ_del_dec.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/PLC.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/VQ_WMat_EC.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/ana_filt_bank_1.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/biquad_alt.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/bwexpander.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/bwexpander_32.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/check_control_input.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/code_signs.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/control_SNR.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/control_audio_bandwidth.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/control_codec.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/debug.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/dec_API.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/decode_core.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/decode_frame.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/decode_indices.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/decode_parameters.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/decode_pitch.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/decode_pulses.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/decoder_set_fs.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/enc_API.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/encode_indices.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/encode_pulses.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/gain_quant.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/HP_variable_cutoff.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/init_decoder.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/init_encoder.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/inner_prod_aligned.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/interpolate.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/lin2log.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/log2lin.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/pitch_est_tables.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/process_NLSFs.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/quant_LTP_gains.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/resampler.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/resampler_down2.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/resampler_down2_3.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/resampler_private_AR2.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/resampler_private_IIR_FIR.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/resampler_private_down_FIR.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/resampler_private_up2_HQ.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/resampler_rom.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/shell_coder.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/sigm_Q15.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/sort.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/stereo_LR_to_MS.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/stereo_MS_to_LR.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/stereo_decode_pred.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/stereo_encode_pred.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/stereo_find_predictor.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/stereo_quant_pred.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/sum_sqr_shift.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/table_LSF_cos.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/tables_LTP.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/tables_NLSF_CB_NB_MB.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/tables_NLSF_CB_WB.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/tables_gain.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/tables_other.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/tables_pitch_lag.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/tables_pulses_per_block.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/VAD.c
)

# SILK fixed-point sources (user must place these in libopus/src/silk/fixed/)
set(SILK_FIXED_SOURCES
    # All files from the original SILK_FIXED_SOURCES list
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/fixed/LTP_analysis_filter_FIX.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/fixed/LTP_scale_ctrl_FIX.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/fixed/apply_sine_window_FIX.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/fixed/autocorr_FIX.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/fixed/burg_modified_FIX.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/fixed/corrMatrix_FIX.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/fixed/encode_frame_FIX.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/fixed/find_LPC_FIX.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/fixed/find_LTP_FIX.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/fixed/find_pitch_lags_FIX.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/fixed/find_pred_coefs_FIX.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/fixed/k2a_FIX.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/fixed/k2a_Q16_FIX.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/fixed/noise_shape_analysis_FIX.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/fixed/pitch_analysis_core_FIX.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/fixed/process_gains_FIX.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/fixed/regularize_correlations_FIX.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/fixed/residual_energy16_FIX.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/fixed/residual_energy_FIX.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/fixed/schur64_FIX.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/fixed/schur_FIX.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/fixed/vector_ops_FIX.c
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/fixed/warped_autocorrelation_FIX.c
)

# DO NOT INCLUDE SILK_FLOAT_SOURCES
# set(SILK_FLOAT_SOURCES ... )

target_sources(usermod_opus INTERFACE
    ${OPUSMOD_BINDING_SOURCES}
    ${OPUS_CORE_SOURCES}
    ${CELT_SOURCES}          # User must ensure these are fixed-point compatible
    ${SILK_COMMON_SOURCES}
    ${SILK_FIXED_SOURCES}
)

# Include directories
target_include_directories(usermod_opus INTERFACE
    ${CMAKE_CURRENT_LIST_DIR}/libopus/include  # Public API
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src      # For opus_private.h and its includes of celt/silk headers
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/celt # CELT headers
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk # SILK headers
    ${CMAKE_CURRENT_LIST_DIR}/libopus/src/silk/fixed # SILK fixed-point headers
)

# Compile definitions
target_compile_definitions(usermod_opus INTERFACE
    -DFIXED_POINT=1          # Enable fixed-point arithmetic
    -DDISABLE_FLOAT_API     # Disable float API (if applicable)
    -DOPUS_BUILD             # Building Opus library components
    -DUSE_ALLOCA=0           # Or do not define USE_ALLOCA
    -DEXPORT=""              # For static linking
    -Dinline=inline          # Ensure 'inline' keyword is C99 inline
    -Drestrict=             # Already present

    # Optional: Disable assembly optimizations
    -DDISABLE_OPTIMIZATIONS
    -DDISABLE_HR_TIMER
)

# Link the interface library to the main usermod target
target_link_libraries(usermod INTERFACE usermod_opus)
